#!/bin/sh
git init --bare --shared repos/$1.git

git clone repos/$1.git $1
cd $1
git config user.email "you@example.com"
git config user.name "Your Name"
git add README.md
git commit -m "creation"

git push origin master
rm -rf $1
