#!/bin/bash

#
# Title: task
#
# Description:
#   This script wraps calling EFF/Let's Encrypt certbot to get certificates for
#   the specified domain(s). This script will be executed by cron, and therefore
#   the certificates will be renewed on the specified frequency.
#
#   Docker container cron-template requires a script called task to implement
#   the function that is to be executed by cron. This script fulfils that
#   requirement.
#
# Usage:
#   Run this script in a crontab, for example, using a "concrete" instance of
#   Docker container cron-template.
#
#   Expects the following environment variables:
#       CERT_DOMAIN - Mandatory: comma separated list of domains, no white space
#       example: CERT_DOMAIN=abc.com,www.xyz.com,mail.xyz.com
#
#       YOUR_EMAIL - Optional: email address to send to EFF. If not given we try
#       --register-unsafely-without-email switch on certbot
#       example: YOUR_EMAIL=name@org.com
#
#       STAGING - Optional: set staging to anything to use production servers
#       if STAGING isn't set, the default is to use --staging with certbot
#       example: STAGING=no
#
# Maintainer:
#   dr.j.osborne@gmail.com
#
# License:
#   MIT, see LICENSE file in repository root
#

set -euo pipefail

# Exit if no domain or list of domains has been specified:
: "${DOMAINS_LISTS:?Domains must be specified: -e "DOMAINS_LISTS=<domain>"}"

# DOMAINS_LIST is a ;-separated list of ,-separated lists of domains
# Structure of DOMAINS_LISTS is cn1,san1,san2-1,..,sanN;cn2,san2-1,...cnN,sanN-M
IFS=';' read -ra ARRAY_OF_LISTS <<< "$DOMAINS_LISTS"

# Each element of ARRAY_OF_LISTS now contains ,-separated domain lists
# Structure of an DOMAINS is cn1,san1-1,san1-2,...san1-M
for DOMAINS in "${ARRAY_OF_LISTS[@]}"; do
    # The first domain in the comma-separated list is the CN
    CN=$(echo $DOMAINS | cut -f1 -d,)

    if [ -d "/etc/letsencrypt/live/${CN}" ]; then
        # Then we already have certs for the CN and SAN(s),
        # so renew this domain's certificates
        #certbot renew # JO 2018-11-22 this doesn't work
        certbot renew --standalone --preferred-challenges http
    else
        # There are no certs for this CN, SAN(s) so get them:

        # Check if an email has been supplied, otherwise send the flag
        # --register-unsafely-without-email
        EMAIL_CMD=${YOUR_EMAIL:---register-unsafely-without-email}
        if [[ "${EMAIL_CMD}" != --register-unsafely-without-email ]]; then
            EMAIL_CMD="--email $EMAIL_CMD"
        fi

        # Using the staging server is the default
        # To use the production server: -e "STAGING=no"
        STAGING=${STAGING:---staging}
        STAGING_CMD=""
        if [[ "${STAGING}" = --staging ]]; then
            STAGING_CMD="--staging"
        fi

        # Recall DOMAINS here is a ,-separated list of domains per the certbot
        # spec
        certbot certonly --standalone $STAGING_CMD $EMAIL_CMD --agree-tos \
            --no-eff-email -d $DOMAINS
    fi
    # Loop for other domain lists
done

